name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy-iac:
    name: Destroy IaC with CDKTF
    runs-on: ubuntu-latest
    env:
      TF_VAR_project: ${{ vars.TF_VAR_project }}
      TF_VAR_service: ${{ vars.TF_VAR_service }}
      TF_VAR_env: ${{ vars.TF_VAR_env }}
      TF_VAR_region: ${{ vars.TF_VAR_region }}
      TF_VAR_container_port: ${{ vars.TF_VAR_container_port }}
      TF_VAR_image_tag: ${{ vars.TF_VAR_image_tag }}
      TF_VAR_az1: ${{ vars.TF_VAR_az1 }}
      TF_VAR_az2: ${{ vars.TF_VAR_az2 }}
      TF_VAR_task_cpu: ${{ vars.TF_VAR_task_cpu }}
      TF_VAR_task_memory: ${{ vars.TF_VAR_task_memory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_region }
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: iac/package-lock.json
      - name: Use Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install IaC dependencies
        working-directory: ./iac
        run: npm ci
      - name: Synthesize Terraform
        working-directory: ./iac
        run: npm run synth
      - name: Destroy Infrastructure (cdktf destroy)
        working-directory: ./iac
        run: npm run destroy