name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  app-ci:
    name: Build, Lint, Test, Compile
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: ./app
        run: npm ci
      - name: Lint source code
        working-directory: ./app
        run: npm run lint
      - name: Run tests
        working-directory: ./app
        run: npm test
      - name: Build TypeScript
        working-directory: ./app
        run: npm run build

  deploy-iac:
    name: Deploy IaC with CDKTF
    runs-on: ubuntu-latest
    needs: app-ci
    env:
      TF_VAR_project: ${{ vars.TF_VAR_project }}
      TF_VAR_service: ${{ vars.TF_VAR_service }}
      TF_VAR_env: ${{ vars.TF_VAR_env }}
      TF_VAR_region: ${{ vars.TF_VAR_region }}
      TF_VAR_container_port: ${{ vars.TF_VAR_container_port }}
      TF_VAR_image_tag: ${{ github.sha }}
      TF_VAR_az1: ${{ vars.TF_VAR_az1 }}
      TF_VAR_az2: ${{ vars.TF_VAR_az2 }}
      TF_VAR_task_cpu: ${{ vars.TF_VAR_task_cpu }}
      TF_VAR_task_memory: ${{ vars.TF_VAR_task_memory }}
    outputs:
      ecr_repository_url: ${{ steps.tf_outputs.outputs.ECR_REPOSITORY_URL }}
      ecr_registry_host: ${{ steps.tf_outputs.outputs.ECR_REGISTRY_HOST }}
      ecr_repository_name: ${{ steps.tf_outputs.outputs.ECR_REPOSITORY_NAME }}
      health_check_url: ${{ steps.tf_outputs.outputs.HEALTH_CHECK_URL }}
      ecs_service_name: ${{ steps.tf_outputs.outputs.ECS_SERVICE_NAME }}
      ecs_cluster_name: ${{ steps.tf_outputs.outputs.ECS_CLUSTER_NAME }}
      alb_dns_name: ${{ steps.tf_outputs.outputs.ALB_DNS_NAME }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_region }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: iac/package-lock.json
      - name: Use Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install IaC dependencies
        working-directory: ./iac
        run: npm ci
      - name: Synthesize Terraform
        working-directory: ./iac
        run: npm run synth
      - name: Deploy IaC (cdktf deploy)
        working-directory: ./iac
        run: npm run deploy
      - name: Export Terraform Outputs
        id: tf_outputs
        working-directory: ./iac
        run: |
          npx cdktf outputs --skip-synth --outputs-file tf_output.json
          ECR_REPOSITORY_URL=$(jq -r '.iac.ecr_repository_url' tf_output.json)
          ECR_REGISTRY_HOST=$(jq -r '.iac.ecr_registry_host' tf_output.json)
          ECR_REPOSITORY_NAME=$(jq -r '.iac.ecr_repository_name' tf_output.json)
          HEALTH_CHECK_URL=$(jq -r '.iac.health_check_url' tf_output.json)
          ECS_SERVICE_NAME=$(jq -r '.iac.ecs_service_name' tf_output.json)
          ECS_CLUSTER_NAME=$(jq -r '.iac.ecs_cluster_name' tf_output.json)
          ALB_DNS_NAME=$(jq -r '.iac.alb_dns_name' tf_output.json)

          echo "ECR_REPOSITORY_URL=$ECR_REPOSITORY_URL"     >> $GITHUB_OUTPUT
          echo "ECR_REGISTRY_HOST=$ECR_REGISTRY_HOST"       >> $GITHUB_OUTPUT
          echo "ECR_REPOSITORY_NAME=$ECR_REPOSITORY_NAME"   >> $GITHUB_OUTPUT
          echo "HEALTH_CHECK_URL=$HEALTH_CHECK_URL"         >> $GITHUB_OUTPUT
          echo "ECS_SERVICE_NAME=$ECS_SERVICE_NAME"         >> $GITHUB_OUTPUT
          echo "ECS_CLUSTER_NAME=$ECS_CLUSTER_NAME"         >> $GITHUB_OUTPUT
          echo "ALB_DNS_NAME=$ALB_DNS_NAME"                 >> $GITHUB_OUTPUT

  image-build-push:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: deploy-iac
    env:
      AWS_REGION: ${{ vars.TF_VAR_region }}
      TF_VAR_image_tag: ${{ github.sha }}
    steps:
      - name: Debug Outputs
        run: |
          echo "Repo URL: ${{ needs.deploy-iac.outputs.ecr_repository_url }}"
          echo "Registry Host: ${{ needs.deploy-iac.outputs.ecr_registry_host }}"
          echo "Repo Name: ${{ needs.deploy-iac.outputs.ecr_repository_name }}"
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region:            ${{ env.AWS_REGION }}
      # - name: Login to Amazon ECR
      #   uses: aws-actions/amazon-ecr-login@v2

      # - name: Build Image
      #   working-directory: ./app
      #   run: |
      #     docker build -t ${{ needs.deploy-iac.outputs.ecr_repository_url }}:${{ env.TF_VAR_image_tag }} .
      # - name: Push Image
      #   run: docker push ${{ needs.deploy-iac.outputs.ecr_repository_url }}:${{ env.TF_VAR_image_tag }}
  
  ecs-deploy:
    name: Update ECS Service to New Image
    runs-on: ubuntu-latest
    needs: 
      - deploy-iac
      - image-build-push
    env:
      AWS_REGION: ${{ vars.TF_VAR_region }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}
      - name: Load deployment metadata
        run: |
          echo "ECR_REPOSITORY_URL=${{ needs.deploy-iac.outputs.ecr_repository_url }}" >> $GITHUB_ENV
          echo "ECS_SERVICE_NAME=${{ needs.deploy-iac.outputs.ecs_service_name }}" >> $GITHUB_ENV
          echo "ECS_CLUSTER_NAME=${{ needs.deploy-iac.outputs.ecs_cluster_name }}" >> $GITHUB_ENV
          echo "TG_URL=http://${{ needs.deploy-iac.outputs.alb_dns_name }}/health" >> $GITHUB_ENV
      # - name: Describe current Task Definition
      #   id: describe_task
      #   run: |
      #     TASK_ARN=$(aws ecs describe-services \
      #       --cluster "$ECS_CLUSTER_NAME" \
      #       --services "$ECS_SERVICE_NAME" \
      #       --query "services[0].taskDefinition" \
      #       --output text)
      #     echo "TASK_ARN=$TASK_ARN" >> $GITHUB_ENV

      # - name: Create new Task Definition revision with new image
      #   id: new_taskdef
      #   run: |
      #     # Download current task definition JSON
      #     aws ecs describe-task-definition \
      #       --task-definition "$TASK_ARN" \
      #       --query "taskDefinition" \
      #       > taskdef.json

      #     # Modify only the container image
      #     NEW_IMAGE="${{ needs.deploy-iac.outputs.ecr_repository_url }}:${IMAGE_TAG}"

      #     # Update image with jq
      #     cat taskdef.json | \
      #       jq ".containerDefinitions[0].image = \"$NEW_IMAGE\"" \
      #       > new-taskdef.json

      #     # Register new revision
      #     NEW_TASKDEF_ARN=$(aws ecs register-task-definition \
      #       --cli-input-json file://new-taskdef.json \
      #       --query "taskDefinition.taskDefinitionArn" \
      #       --output text)

      #     echo "NEW_TASKDEF_ARN=$NEW_TASKDEF_ARN" >> $GITHUB_ENV

      # - name: Update ECS Service to new revision
      #   run: |
      #     aws ecs update-service \
      #       --cluster "$ECS_CLUSTER_NAME" \
      #       --service "$ECS_SERVICE_NAME" \
      #       --task-definition "$NEW_TASKDEF_ARN"

      # - name: Wait for ECS deployment to stabilize
      #   run: |
      #     aws ecs wait services-stable \
      #       --cluster "$ECS_CLUSTER_NAME" \
      #       --services "$ECS_SERVICE_NAME"

      # - name: Show Health Check URL
      #   run: |
      #     echo "Deployment successful!"
      #     echo "Health Check URL:"
      #     echo "${TG_URL}"
