name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  app-ci:
    name: Build, Lint, Test, Compile
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: ./app
        run: npm ci
      - name: Lint source code
        working-directory: ./app
        run: npm run lint
      - name: Run tests
        working-directory: ./app
        run: npm test
      - name: Build TypeScript
        working-directory: ./app
        run: npm run build

  deploy-iac:
    name: Deploy IaC with CDKTF
    runs-on: ubuntu-latest
    needs: app-ci
    env:
      TF_VAR_project: turbo
      TF_VAR_service: api
      TF_VAR_env: dev
      TF_VAR_region: us-east-2
      TF_VAR_container_port: 3000
      TF_VAR_image_tag: latest
      TF_VAR_az1: us-east-2a
      TF_VAR_az2: us-east-2b
      TF_VAR_task_cpu: 256
      TF_VAR_task_memory: 512
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_region }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: iac/package-lock.json
      - name: Use Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install IaC dependencies
        working-directory: ./iac
        run: npm ci
      - name: Synthesize Terraform
        working-directory: ./iac
        run: npm run synth
      - name: Deploy IaC (cdktf deploy)
        working-directory: ./iac
        run: npm run deploy